User story 11 world map
Oskmey/-Agile-software-project-management pull request #101
Opened 2024-04-17 14:39 UTC by ludwigal

Might not need handleminigameonwon/lost in minigamemanager.

2024-04-17 15:53 UTC, Caramajau commented on DAT257AgileProject/Assets/InitTestScene638488155537240292.unity
This scene shouldn't exist, it was probably created accidentely during a test.

2024-04-17 15:56 UTC, Caramajau commented on DAT257AgileProject/Assets/InitTestScene638488155537240292.unity.meta
This iss the meta file for the unnecessary scene.

2024-04-17 16:01 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    private GameObject trashPrefab;    // TODO Make it possible to have many types of trash
This shouldn't be here, this is the third time this has to be removbed, the prefabs are set in the factoryand shouldn't be hard-coded here.

2024-04-17 16:05 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Player/PlayerController.cs
> +    }
Is the missspelling of Movement intentional?

2024-04-17 16:08 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
> +        //hideTrashInfoPanelAction = playerInput.actions["HideTrashInfoPanel"];
Why has this been commented out? also the info box doesn't seem to show up?

2024-04-17 16:13 UTC, Caramajau requested changes
Lastly, it doesn't seem possible to properly run the program from the menu scene and it gives a lot of errors at the start and during the game. I tried playing it through "Oscar's World" where there were some errors and a lot of debug prints. Some of these prints might be necessary before actual features are implemented, but there are a lot and maybe some should be removed. 

Also the infobox is no where to be found in the game and the trash is never removed in the world. This is most likely due to what one comment above points out and it is that the hideTrashInfoBoxAction is commented out. Also the GameplayHUD shouldn't be part of the world space I believe, which is why the info box probably isn't shown in the part of the world that can be accessed, and is likely actually shown really far away.

2024-04-17 18:05 UTC, HugoUnosson commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    private GameObject trashPrefab;    // TODO Make it possible to have many types of trash
This was originally a "popup cool trash effect" that appeared when winning the minigame, however it was never used. And yes it should be removed since it was only for the mvp.

2024-04-17 18:09 UTC, HugoUnosson commented
I agree with David, it should be merged into sprint 3, especially now when Linus is merging sprint 2 -> main at the same time. BTW I can't add a review because chrome chrashes, probably due to too many changed files

2024-04-17 18:52 UTC, linuskar commented
need to resolve the conflicts from the recent pull request done to sprint 3

2024-04-18 08:45 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Player/PlayerController.cs
> +    }
No

2024-04-18 08:49 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
> +        //hideTrashInfoPanelAction = playerInput.actions["HideTrashInfoPanel"];
Probably some result of debugging that accidentally got into the code. Will fix

2024-04-18 08:54 UTC, Oskmey commented on DAT257AgileProject/Assets/InitTestScene638488155537240292.unity
Yes, these scenes are created when running play mode without loading a scene. Will fix

2024-04-18 09:19 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Player/PlayerController.cs
> +    }
Fixed

2024-04-18 09:29 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
> +        //hideTrashInfoPanelAction = playerInput.actions["HideTrashInfoPanel"];
This had been changed

2024-04-18 09:30 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    private GameObject trashPrefab;    // TODO Make it possible to have many types of trash
This now uses TrasHandler

2024-04-18 13:36 UTC, Caramajau approved these changes

2024-04-18 14:02 UTC, HermanForsberg approved these changes
its good stuff

2024-04-18 14:05 UTC, merged