User story 9 walkable player
Oskmey/-Agile-software-project-management pull request #104
Opened 2024-04-18 16:04 UTC by HugoUnosson

2024-04-18 17:30 UTC, Caramajau commented
Game crashed after fishing once.
![game_crash](https://github.com/Oskmey/-Agile-software-project-management/assets/90894366/7fd78a7e-9569-497a-9666-7f0906c2aa42)

2024-04-18 17:33 UTC, Caramajau commented
> Game crashed after fishing once. ![game_crash](https://private-user-images.githubusercontent.com/90894366/323703101-7fd78a7e-9569-497a-9666-7f0906c2aa42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjE3NDcsIm5iZiI6MTcxMzQ2MTQ0NywicGF0aCI6Ii85MDg5NDM2Ni8zMjM3MDMxMDEtN2ZkNzhhN2UtOTU2OS00OTdhLTk2NjYtN2YwOTA2YzJhYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE3MzA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZDMyOTZhMGE1YzdhZjc3ODM3ZjY2ZjRkYzQwMWI5ZTYwNmFhMmE2YjlhZWMxNzEzMDE5OTZjMjYzNjRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6sZ1uUnEyQv5MU_zdFzGeXnN-oD8Efrw8HwFBQGTMNo)

It seems like it is inconsitent and only happens when some kind of combination of inputs is done.

2024-04-18 17:43 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    public bool isPlayingMinigame { get; private set; }
Why is "isFishing" public? and if it has to be at least use a setter or property.

2024-04-18 17:44 UTC, HugoUnosson commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    public bool isPlayingMinigame { get; private set; }
Just forgot to change it back to private

2024-04-18 17:48 UTC, Caramajau requested changes
See comment about public field, saw now that the game crash exists in sprint_3 as well.

2024-04-19 11:38 UTC, HugoUnosson commented
Updated the sprites for minigama and exclamation mark

2024-04-19 11:41 UTC, HugoUnosson commented
> See comment about public field, saw now that the game crash exists in sprint_3 as well.

And btw I did not try to fix the bug since it probably has to do with something else than animations??

2024-04-19 12:54 UTC, Caramajau approved these changes
For me it's fine now.

2024-04-19 12:55 UTC, Caramajau commented
> I think it is well implemented except for some bugs. One thing is that you start fishing without evan pressing f (maybe its a feature i dont know). Also when I catch something and dont close the info window and start fishing again I get stuck and cant get out of fishing or the info screen.

I believe it is intentional that you fish when you touch the water tile, don't know anything about the other bug though.

2024-04-22 09:18 UTC, HugoUnosson commented
> I think it is well implemented except for some bugs. One thing is that you start fishing without evan pressing f (maybe its a feature i dont know). Also when I catch something and dont close the info window and start fishing again I get stuck and cant get out of fishing or the info screen.

Yes it is a feature. Dont know why you get stuck, it seems to happen in other branches too

2024-04-22 19:05 UTC, HermanForsberg approved these changes

2024-04-22 21:03 UTC, merged