User story 23 facts screen
Oskmey/-Agile-software-project-management pull request #110
Opened 2024-04-22 11:56 UTC by HermanForsberg

Now the facts/wkik page is implemented in the main menu! It should show all the facts (and sources) with a subheader for the different trash we have implemented facts for. You should also be able to click the source to go to the webpage

2024-04-22 12:25 UTC, HugoUnosson approved these changes
Good job Herman, horrible choice of colors though, my eyes hurt

2024-04-22 12:25 UTC, HermanForsberg commented
hahah fair enough

2024-04-22 13:15 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
Unsure if this file should need to be changed, I believe you have made some updates only in the scene version of the prefab, is there any reason for this or did you just forget?

2024-04-22 13:28 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Menus/WikiHandler.cs
> +            sourcesText += $"\n- {source.SourceName} ({source.Date}) <i>{source.Title}</i> {source.Website}";
You should also display the retrieval date in this menu, we is just adding retrieved ({{source.RetrievalDate}) to the string. (The reason I didn't do this in-game was to save space).

2024-04-22 13:35 UTC, Caramajau requested changes
Lastly, I think there is one important change that could be done, but if it is too difficult it could maybe be saved for future sprints. Which is that it would be nice for each subheading to have its own page with its own scrollbar instead of every fact being in a long scrollbar. Right now I find it quite difficult to navigate the menu. 

UPDATE: forgot to mention that I get this warning. Why?
![warning_project](https://github.com/Oskmey/-Agile-software-project-management/assets/90894366/d54e5d67-6938-459d-b011-cf874488cdac)

2024-04-23 07:39 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
I forgot to update the prefab with some small last minute changes! The prefab is up to date now tho

2024-04-23 07:39 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Menus/WikiHandler.cs
> +            sourcesText += $"\n- {source.SourceName} ({source.Date}) <i>{source.Title}</i> {source.Website}";
My thought was that this wasn't necessary, but I can add it if we want to show it. Not a hard change at all.

2024-04-23 07:42 UTC, HermanForsberg commented
> Lastly, I think there is one important change that could be done, but if it is too difficult it could maybe be saved for future sprints. Which is that it would be nice for each subheading to have its own page with its own scrollbar instead of every fact being in a long scrollbar. Right now I find it quite difficult to navigate the menu.
> 
> UPDATE: forgot to mention that I get this warning. Why? ![warning_project](https://private-user-images.githubusercontent.com/90894366/324480958-d54e5d67-6938-459d-b011-cf874488cdac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTgyNjUsIm5iZiI6MTcxMzg1Nzk2NSwicGF0aCI6Ii85MDg5NDM2Ni8zMjQ0ODA5NTgtZDU0ZTVkNjctNjkzOC00NTlkLWIwMTEtY2Y4NzQ0ODhjZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3MzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MmI1OTZhN2I0NDg5OWY3YTA4N2IyYTE5ODMzZTU3ZTViMWZiNmE1MWMyMmRhOTA1MTAyYjRlYWUyNWIzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zmf6vAuH_8uGeBNwhfMbUI4YiOJjhd3bOP6X1SrzPmw)

I didn't get the warning so I have no idea, I will look into it! And I agree that it would be a cleaner design, it would mean some restructuring. Maybe we can come back to that change if we feel that we have time over?

2024-04-24 20:15 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Menus/WikiHandler.cs
> +            sourcesText += $"\n- {source.SourceName} ({source.Date}) <i>{source.Title}</i> {source.Website}";
now retrieval date is added

2024-04-25 07:46 UTC, Caramajau approved these changes

2024-04-26 08:33 UTC, merged