User story 13 different types of water
Oskmey/-Agile-software-project-management pull request #111
Opened 2024-04-22 15:11 UTC by ludwigal

The solution for different rarities at different percentages feels very inefficient(please come with ideas if you have any). Common rarity is always ticked in the code but not in unity since it is awful to work with(It doesnt matter if common is ticked in unity). I also added a "Do not use everything" option since if you select everything you do not actually get all the rarities into the code you get the option "Everything" and that only returns -1, which is also awful to work with. We could use TrashRarity for this instead of FishingSpotRarities but then we have to make TrashRarity flags which I dont think we want.

2024-04-22 17:55 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Oskar's World.unity
> +      propertyPath: m_Name
I believe you accidentally added a trash bag to the world, or should it be there?

2024-04-22 17:57 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
>      private static bool isFishing = true;
I think the fs variable is unused?

2024-04-22 17:58 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +//Need to add percentages I guess
I think Unity's randomiser system is to prefer, but this should work.

2024-04-22 18:00 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +}
This method doesn't use the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:00 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
>      }
This method doesn't use the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:01 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +
This method doesn't use the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:01 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    }
This method doesn't use the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:01 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +                    break;
Would look nice if you used proper indentation here as well as the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:08 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +
I do agree that this system feels a little bit overcomplicated, however I can't come up with a better solution right now.

2024-04-22 18:10 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
>      }
Why is there an empty method?

2024-04-22 18:11 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
> +            }
This method doesn't fully use the [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) style.

2024-04-22 18:14 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpotRarities.cs
> +
This enum is really ugly with its whitespaces, but I don't think it is breaking any conventions, except maybe that the [Flags] should be on a line above the "public enum FishingSpotRarities".

2024-04-22 18:16 UTC, Caramajau requested changes
See comments.

2024-04-23 12:23 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +
I think I figured out an alternative way that might be better. Maybe it could be that the method that decides the rarity takes in a probability vector (represented as maybe an array) and then in the method converts its memebers into cumulative sum values. Then you randomise a number netween 0 and 1 and using this you loop through the vector and see if the number is less or equal to the cumaltive sum for each rarity. Since you will loop through the vector using indices you could then convert the current index to the trash rarity enum and return it. 

I think this will probabiliy be a simpler solution and the probability values could easily be set differently for each water. 

The main issue with this solution is that it will probably be a little bit more difficult if we want to add more rarities in the future.

2024-04-23 14:53 UTC, Caramajau commented
This is a comment unrelated to the reviews, but a recommendation for solving the scene merge conflict is choosing your version over the current one in the sprint branch. To get the changes from the sprint branch to your version, Edgar can help you.

2024-04-23 18:20 UTC, ludwigal commented on DAT257AgileProject/Assets/Scenes/Oskar's World.unity
> +      propertyPath: m_Name
fixed

2024-04-23 18:21 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
>      private static bool isFishing = true;
fixed

2024-04-23 18:21 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +}
fixed

2024-04-23 18:21 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +
fixed

2024-04-23 18:22 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +                    break;
fixed

2024-04-23 18:23 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
>      }
fixed

2024-04-23 18:23 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
> +            }
fixed

2024-04-23 18:24 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpotRarities.cs
> +
fixed, was because common should always be ticked, but it was awful to use in unity.

2024-04-23 19:33 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +
I think I have changed to this solution succesfully, please check and tell me If you can find anything that looks wrong/bad :-). Only "problem" with this is that I have not set a constraint so you have to check for yourself that the percentages add up to 100%, otherwise the calculations will be off.

2024-04-24 05:57 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
> +    float randomNumber = UnityEngine.Random.Range((float)0.0,(float)1.0);
Could probably use this? https://docs.unity3d.com/ScriptReference/Random-value.html

2024-04-24 10:39 UTC, Caramajau approved these changes

2024-04-24 10:40 UTC, HermanForsberg approved these changes
Looks good fam

2024-04-24 11:00 UTC, merged