User story 22: Animations for recycling
Oskmey/-Agile-software-project-management pull request #112
Opened 2024-04-23 13:38 UTC by AronLundh

2024-04-23 15:01 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +                if (isRecycling)
Able to walk around with the recycle animation because the local value in player animations is only updated when in range of recycle machine.

2024-04-23 15:02 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +        }
Would be nice if you removed this debug log before merging because it spams the console with logs.

2024-04-23 15:06 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +        animator.SetBool("isRecycling", isRecycling);
Is the local version of the isRecycling necessary, or could you directly get the value from the recycling mananger?

2024-04-23 15:08 UTC, Caramajau commented
Lastly, it might be worth trying to merge in sprint_3 to the branch before merging since this one is now based on a more outdated version than most other branches, just to double check that everything works.

2024-04-23 15:35 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +                if (isRecycling)
Showcase of the bug.
![recycle_bug](https://github.com/Oskmey/-Agile-software-project-management/assets/90894366/14464137-139f-43ef-a9ac-4487e82b7441)

2024-04-25 07:32 UTC, ludwigal reviewed
I also think we maybe should look over the ordering of layers so that we can see the animation standing besides the machine (maybe in antoher branch/user story, idk).

2024-04-25 07:32 UTC, ludwigal commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +            }
Like David commented there should be an else statement here that sets isRecycling=false to cancel the animation.

2024-05-14 13:38 UTC, AronLundh commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +        }
Fixed this

2024-05-14 13:49 UTC, AronLundh commented on DAT257AgileProject/Assets/Scripts/Player/PlayerAnimations.cs
> +            }
I did not resolve this since we use don't use the local variable now

2024-05-14 17:26 UTC, linuskar requested changes
Update this branch by merge the current sprint branch (sprint 5) into this one and resolve the conflicts.

2024-05-16 14:41 UTC, closed without merging