added menu music background music and credits
Oskmey/-Agile-software-project-management pull request #135
Opened 2024-05-05 12:04 UTC by Figer-op

did adde music from to ther game and credits

2024-05-05 12:24 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
I think it would be good to create prefabs for the music player so that scene conflicts will be easier to solve. The Save branch has made changes to this scene.

2024-05-05 12:25 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
Also the game now starts with the credits screen for some reason, it should start with the main menu. (I'm guessing you've made the credits scene active by default)

2024-05-05 12:26 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Oskar's World.unity
I think it would be good to create prefabs for the music player so that scene conflicts will be easier to solve. I believe the inventory branch has made changes to this scene.

2024-05-05 12:26 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Oskar's World.unity
Also right now we have in the sprint branch that Oskar's world is first loaded, but when existing the shop you spawn in the First World scene, where there is no music player, thus no music. Probably should be fixed.

2024-05-07 06:55 UTC, Caramajau requested changes
Shop should probably have theme (will send one, maybe it is good).

2024-05-07 10:45 UTC, Caramajau approved these changes

2024-05-08 08:30 UTC, linuskar approved these changes
good

2024-05-08 08:31 UTC, merged