User story 16 create a new world
Oskmey/-Agile-software-project-management pull request #142
Opened 2024-05-08 14:52 UTC by Oskmey

Second World
![Skärmbild 2024-05-08 165057](https://github.com/Oskmey/-Agile-software-project-management/assets/112823957/e1ce068c-4fa1-41ab-8a8c-d61c40ac22e8)

2024-05-09 11:13 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/Second World.unity
Looks good. Though it would probably be nice to have the second map as a prefab.

2024-05-09 11:14 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/Second World.unity
Maybe it is also possible to make the intended fishing spot a little clearer?

2024-05-10 16:25 UTC, Oskmey commented on DAT257AgileProject/Assets/Scenes/Game/Second World.unity
Yes, we considered changing the texture of the fishing spots to accurately reflect that those places are polluted.

2024-05-12 19:38 UTC, Oskmey commented on DAT257AgileProject/Assets/Scenes/Game/Second World.unity
Added some texture for fishing spot to make it clearer that you could fish there and made map a prefab with the fishingspots

2024-05-12 19:38 UTC, Oskmey commented
Added fishingspot textures

2024-05-12 20:19 UTC, Caramajau approved these changes

2024-05-13 09:55 UTC, linuskar requested changes
Add credits for the second world

2024-05-13 12:01 UTC, linuskar approved these changes
ok

2024-05-13 12:01 UTC, merged