User story 20 sound effects
Oskmey/-Agile-software-project-management pull request #148
Opened 2024-05-14 15:45 UTC by Figer-op

add description here ... jag är klkar

2024-05-14 16:35 UTC, Caramajau commented on DAT257AgileProject/Assets/Scenes/Game/First World.unity
Why change?

2024-05-14 16:59 UTC, Caramajau commented on DAT257AgileProject/Assets/Resources/ScriptableObjects/Audio/Sound/ExclamationMarkAppears.asset
Should maybe be a little quieter?

2024-05-14 16:59 UTC, Caramajau commented on DAT257AgileProject/Assets/Resources/ScriptableObjects/Audio/Sound/StartFishSound.asset
Should maybe be a little quieter?

2024-05-14 17:01 UTC, Caramajau requested changes
Lastly you should probably update the credits, though you might want to wait with that since User Story 32 and User Story 29 has done things in the main menu. After that I believe no other User Story should affect the main menu, but could be wrong.

2024-05-15 13:32 UTC, Caramajau approved these changes

2024-05-16 12:13 UTC, Oskmey approved these changes
LGTM

2024-05-16 16:17 UTC, merged