User story 14 first accessory
Oskmey/-Agile-software-project-management pull request #149
Opened 2024-05-15 09:37 UTC by HermanForsberg

The egg now gives a movement speed boost. There are some wonky bugs that happen when you equip more than 1 egg

2024-05-15 10:19 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Trash/TrashData.cs
> +    public int moneyValue { get; set; } // I dunno if this is ok
Why did you change this? there is already a getter for the money value and it shouldn't change during runtime

2024-05-15 10:20 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/effect.cs
Why empty class?

2024-05-15 10:21 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/SpeedEffect.cs
Is this used?

2024-05-15 10:22 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +                trashData.moneyValue *= 2;
You should probably have it multiply the standard value when given to the player, rather than changing the actual value

2024-05-15 10:26 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/SpeedEffect.cs
No! I have deleted it in

2024-05-15 10:26 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/effect.cs
should have been deleted! fixed it now

2024-05-15 10:28 UTC, Caramajau requested changes
CRITICAL: I'm not getting money from recycling.

2024-05-15 17:34 UTC, linuskar commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +                trashData.moneyValue *= 2;
this is being changed in the next user story for accessories, for rare egg

2024-05-15 19:04 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/AEffect.cs
> +
What is the point of AEffectExtensions?

2024-05-15 19:06 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/AEffect.cs
> +
This should also be deleted hehe. We tried a few different approaches and forgot to delete certain parts

2024-05-15 19:07 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/AEffect.cs
> +
I will delete it tomorrow

2024-05-15 19:07 UTC, Caramajau commented on DAT257AgileProject/Assets/Resources/ScriptableObjects/Shop/Egg.asset
> +  - {fileID: 11400000, guid: 04e30a241610a5c4da1593ce9b3d09f0, type: 2}
Maybe the effect should have a better name than "testEffect"

2024-05-15 19:08 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
I'm guessing MoneyEffect is a work in progress and is meant for a future branch?

2024-05-15 19:08 UTC, HermanForsberg commented
> moneyValue

Yes I saw this when I made the branch for user story 15. I fixed it in that branch, so if we merge this first and then add US15 on top of that it shouldnt be an issue

2024-05-15 19:09 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
yes

2024-05-15 19:09 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
Saw comment now.

2024-05-15 19:09 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
user story 15

2024-05-15 19:09 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Resources/ScriptableObjects/Shop/Egg.asset
> +  - {fileID: 11400000, guid: 04e30a241610a5c4da1593ce9b3d09f0, type: 2}
is deleted in branch 15

2024-05-16 12:26 UTC, Oskmey reviewed
> [!WARNING]  
> LGTM, jag tror att några grejor använder UnityEditor istället för Unity. Detta kommer leda till att vi inte kommer att kunna göra en build av spelet. :shipit: :shipit:

2024-05-16 12:26 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +                EditorUtility.SetDirty(asset);
I think building the game is impossible with this :shipit:

2024-05-16 12:26 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +        Object[] assets = AssetDatabase.LoadAllAssetsAtPath(folderPath);
I think building the game is impossible with this too :shipit:

2024-05-16 12:26 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +        Object[] assets = AssetDatabase.LoadAllAssetsAtPath(folderPath);
Objects[] assets = Resources.LoadAll<TrashData>("ScriptableObjects/Trash"); could work IDK

2024-05-16 12:27 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +        Object[] assets = AssetDatabase.LoadAllAssetsAtPath(folderPath);
it is deleted in the later branch (user story 15)

2024-05-16 12:28 UTC, HermanForsberg commented on DAT257AgileProject/Assets/Scripts/Accessory/Effects/MoneyEffectSO.cs
> +                EditorUtility.SetDirty(asset);
it is deleted in user story 15

2024-05-16 13:42 UTC, Caramajau approved these changes
I will approve assuming my last comment will be resolved soon.

2024-05-16 14:07 UTC, ludwigal reviewed
Good :)

2024-05-16 14:07 UTC, ludwigal approved these changes

2024-05-16 14:07 UTC, merged