User story 8 create a map
Oskmey/-Agile-software-project-management pull request #151
Opened 2024-05-16 12:01 UTC by Oskmey

Made map select

2024-05-16 13:52 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Map/Ainteractable.cs
> +            Debug.LogWarning("Text is null");
Potentially misleading warning since the condiction also checks if the tag is "Player".

2024-05-16 13:53 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +        container = ui.transform.Find("Scroll View").Find("Viewport").Find("Content").transform;
Would probably be more readable if the Find methods were one line at a time.

2024-05-16 13:55 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    private bool isMapOpen = false;
Is the isMapOpen variable necessary, is it not possible to check whether the UI is active or not?

2024-05-16 13:59 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    }
Is it not possible to reuse the other method, if it is not possible to create a scriptable object for the deault world, maybe the method itself could take the relevant content as parameters?

2024-05-16 14:00 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Shop/ShopInteraction.cs
> +        SceneManager.LoadScene("Shop");
Should maybe be LoadAsync?

2024-05-16 14:23 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    private bool isMapOpen = false;
I believe this issue originates from a previous bug. I also encountered difficulties checking if the UI was active, as it resulted in a null pointer error.

2024-05-16 14:24 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    private bool isMapOpen = false;
nvm there is something called activeSelf will change

2024-05-16 14:35 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    }
Yes, I will look into improving the method. The challenge is that we still need to create the default world

2024-05-16 15:21 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Map/Ainteractable.cs
> +            Debug.LogWarning("Text is null");
fixed

2024-05-16 15:22 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Map/MapInteraction.cs
> +    }
I hope i fixed

2024-05-16 15:23 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Shop/ShopInteraction.cs
> +        SceneManager.LoadScene("Shop");
Fixed

2024-05-16 15:27 UTC, Caramajau approved these changes

2024-05-16 15:38 UTC, Caramajau requested changes
![errors](https://github.com/Oskmey/-Agile-software-project-management/assets/90894366/5ae366a8-fec2-45f4-a8ed-1514f095725d)

There seem to be some errors as a result from a merge maybe?

It looks like shop manager had a script which now doesn't exist?

Saw now that the script is indeed deleted, and the game object was probably deleted in this branch.

2024-05-16 15:47 UTC, Caramajau commented on DAT257AgileProject/Assets/Scripts/Shop/ShopPlayer.cs
> +            Debug.LogError("No matching map found.");
A bit misleading error since it prints when ticket is already bought?

2024-05-17 12:24 UTC, Caramajau approved these changes

2024-05-17 12:25 UTC, linuskar approved these changes

2024-05-17 12:26 UTC, merged