Recycling
Oskmey/-Agile-software-project-management pull request #19
Opened 2024-04-09 12:55 UTC by linuskar

2024-04-09 13:04 UTC, linuskar commented
Ruleset not working for older sprint branches?

2024-04-09 13:06 UTC, linuskar commented
> Ruleset not working for older sprint branches?

![image](https://github.com/Oskmey/-Agile-software-project-management/assets/112468791/9c1eacf2-3a15-4bcf-98aa-c63255574a64)

2024-04-09 14:26 UTC, Oskmey commented
Yes, it should work now. The issue before was that I was using regular regex, but I needed to use fnmatch syntax

2024-04-09 14:27 UTC, Oskmey commented
Yes, it should work now. The issue before was that I was using regular regex, but I needed to use fnmatch syntax

2024-04-09 15:55 UTC, Oskmey requested changes
You can just resolve my comments if you think they are not good.

#  Looks very good!

2024-04-09 15:55 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/GameManager.cs
> +        GenerateTrash(2);
We might overlook removing this when putting everything together.

2024-04-09 15:55 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Player/PlayerStatsManager.cs
> +        money = 0;
I'm not certain, but will this be implemented in the player class later? Could then we add something that stores it between scenes. :zany_face:

2024-04-09 15:55 UTC, Oskmey commented on DAT257AgileProject/Assets/Scripts/Player/PlayerStatsManager.cs
> +        money = 0;
This seems like something we could add when merging everything

2024-04-09 16:42 UTC, Caramajau requested changes
### Looks good in general, however...

### Some minor things that should be changed are:

Spelling mistakes:
- GameManager at line 62 (should be recyclable)
- GameManager at line 69 (should be success)

Better encapsulation in RecyclingManager
- From what I can see the properties in RecyclingManager do not need to have setters, their values are only changed locally in the class or not at all. 
- Also IReadOnlyList as a return type can be used for better encapsulation. 

Other not important spelling mistakes (can ignore if you want):
- RecyclingTests at line 24 (should be recyclable)
- RecyclingTests at line 37 (should be recyclable)
- Recycling machine at line 39 (should be recyclable)

2024-04-09 16:43 UTC, linuskar commented on DAT257AgileProject/Assets/Scripts/GameManager.cs
> +        GenerateTrash(2);
yes

2024-04-09 16:49 UTC, linuskar commented on DAT257AgileProject/Assets/Scripts/GameManager.cs
> +        GenerateTrash(2);
> We might overlook removing this when putting everything together.

Yes

2024-04-09 17:02 UTC, linuskar commented
> ### Looks good in general, however...
> ### Some minor things that should be changed are:
> Spelling mistakes:
> 
> * GameManager at line 62 (should be recyclable)
> * GameManager at line 69 (should be success)
> 
> Better encapsulation in RecyclingManager
> 
> * From what I can see the properties in RecyclingManager do not need to have setters, their values are only changed locally in the class or not at all.
> * Also IReadOnlyList as a return type can be used for better encapsulation.
> 
> Other not important spelling mistakes (can ignore if you want):
> 
> * RecyclingTests at line 24 (should be recyclable)
> * RecyclingTests at line 37 (should be recyclable)
> * Recycling machine at line 39 (should be recyclable)

Commited based on changes

2024-04-09 18:55 UTC, Caramajau approved these changes

2024-04-10 11:06 UTC, Oskmey approved these changes

2024-04-10 11:06 UTC, merged