Fixing tests from user story 17
Oskmey/-Agile-software-project-management pull request #93
Opened 2024-04-16 16:59 UTC by linuskar

Made so we use C# events instead of Unity Events. 
Random trash of common rarity should be fished as of now.
Fixed some old tests not working. Adapted recycling machine tests to use trashdata.

2024-04-16 17:33 UTC, Caramajau commented on DAT257AgileProject/Assets/Tests/EditMode/Recycling/RecyclingTests.cs
>          Assert.IsTrue(isRecycable);
I believe this test will return true no matter what because of the way it gets the test cases. Since both the test and the test cases uses the same property, they will always match.

2024-04-16 17:38 UTC, Caramajau requested changes
Unnecessary usage of TrashData, see comments.

2024-04-17 12:41 UTC, HugoUnosson approved these changes

2024-04-17 14:27 UTC, Caramajau approved these changes

2024-04-17 18:43 UTC, merged